services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db_todo
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: todo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

  adminer:
    image: adminer
    container_name: adminer_task
    ports:
      - '8082:8080'  # Changez le port externe à 8081
volumes:
  postgres-data:
